manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: sekigon-gonnoc  # PAW3222
      url-base: https://github.com/sekigon-gonnoc
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: imo00o
      url-base: https://github.com/imo00o
  projects:
    #　- name: zmk
    #   remote: zmkfirmware
    #   revision: v0.3.0
    - name: zmk
      remote: cormoran
      revision: v0.3-branch+dya
      import: app/west.yml
    - name: zmk-driver-paw3222
      remote: sekigon-gonnoc
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3.0
    # DYA Studio モジュール
    - name: zmk-module-ble-management
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-module-battery-history
      remote: cormoran
      revision: main
    - name: zmk-module-settings-rpc
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-module-runtime-input-processor
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-behavior-runtime-sensor-rotate
      remote: cormoran
      revision: zmk-v0.3.0.0
    # macro, combo, device-info, input-stream, physical-layout, custom-settings
    - name: zmk-feature-runtime-macro
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-feature-runtime-combo
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-feature-device-info
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-feature-input-stream
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-feature-module-physical-layout
      remote: cormoran
      revision: zmk-v0.3.0.0
    - name: zmk-feature-custom-settings
      remote: cormoran
      revision: zmk-v0.3.0.0
  self:
    path: config
